### ISSUE TITLE
[Bugs] Site Formatting Issues?

### ISSUE THREAD

**Issue by jefdo** [pact-foundation/pact.io#28]
Duplicate Introduction
![image](https://user-images.githubusercontent.com/29634950/27445828-2caf8b8c-5730-11e7-9ef4-644095ea1db0.png)

Sidebar has a duplicated title, when it should be something else.
![image](https://user-images.githubusercontent.com/29634950/27445890-63a4c0a8-5730-11e7-95ac-9b0d8075c980.png)

**Comment by TimothyJones** [comment]
Thanks for the report! This is now fixed (#43).
