### ISSUE TITLE
Merge broker documentation into pact.io?

### ISSUE THREAD

**Issue by TimothyJones** [pact-foundation/pact.io#41]
The pact.io documentation should probably include the documentation that's currently in the Broker Wiki, so that documentation is all in one place

**Comment by TimothyJones** [comment]
Updated thinking on this: Pact.io would be better off describing what the broker is, and the wiki holds the detailed documents.

However, it's worth adding a quick link to the broker in the navigation bar

**Comment by YOU54F** [comment]
I believe this is done and these files now exist in https://github.com/pact-foundation/docs.pact.io/tree/master/website/docs/pact_broker

Feel free to re-open if this isn't the case
