### ISSUE TITLE
Travis build fails on documentation branch

### ISSUE THREAD

**Issue by TimothyJones** [pact-foundation/pact.io#44]
When the documentation branch (currently called `test`) builds on travis, it fails because there's no Rake file.

It would be better if the build for the documentation branch provided information about whether the documentation built successfully.

**Comment by mboudreau** [comment]
There is no actual "build" per say.  it's all done with git books.  We can
probably remove the travis file.

**Comment by TimothyJones** [comment]
Update: There isn't a travis file. Perhaps this is handled by the Travis settings

**Comment by mboudreau** [comment]
Ah, I think it's from the master which does.  It used to be jekill that
would build it, and travis is still enabled on it.  I've updated the
settings to only build if a travis file is present.
