### ISSUE TITLE
Unclear documentation.

### ISSUE THREAD

**Issue by Raivias** [pact-foundation/pact.io#48]
Seeing a small issue in the first sentence of [getting started](https://github.com/pact-foundation/pact.io/blob/documentation/getting_started/README.md) specifically "you will need to **and** install the relevant". I'd correct it but I'm new to the framework and not sure how it should read.

May want to give the rest of the document a read through as well.

**Comment by mboudreau** [comment]
Yeah, probably a merge issue somewhere. Will have to revisit it. Thanks.

**Comment by bethesque** [comment]
Fixed the sentence.

**Comment by Raivias** [comment]
Thanks
