### ISSUE TITLE
gists linked to in  pact.io/best_practices/provider.md are invalid

### ISSUE THREAD

**Issue by davidmichaelkarr** [pact-foundation/pact.io#51]
I was viewing pact.io/best_practices/provider.md and I tried to view the two gists linked to from that page.  They both failed with "Secure Connection Failed".  They are actually both links to the same page.

The gist link is https://gist.github.com/bethesque/43eef1bf47afea4445c8b8bdebf28df0 .

**Comment by mboudreau** [comment]
We're in the process of redoing the website and documentation to be more up to date with what's available in each language.

**Comment by mefellows** [comment]
That link works just fine for me. I tried from multiple browsers, including "incognito" modes.

Can you please provide some more detail?

**Comment by davidmichaelkarr** [comment]
Ah.  This appears to be an issue with our company firewall.  I guess I'll have to research that.
