### ISSUE TITLE
What is the difference between Contract driven testing and behavior driven testing?

### ISSUE THREAD

**Issue by Celthi** [pact-foundation/pact.io#79]
I have read some of the documents in the pact.io. I cannot differentiate the CDT and the BDD.
The contract testing seems like giving some request and verifying the response.
So what are the differences between CDT and BDD?

**Comment by bethesque** [comment]
I would suggest you join https://slack.pact.io/ and ask this question there.

**Comment by bethesque** [comment]
Have you read this? https://docs.pact.io/best_practices/consumer/contract_tests_not_functional_tests

**Comment by Celthi** [comment]
@bethesque I'll close it and ask the question in the slack.pact.io.
I have read the link you provide.
From the link I think the pact just specify a loose test case. In BDD, the test case may cover empty string, too long string. While pact will only specify a invalid case such as empty string.
And My second question is there should be different library to do contract driven testing.
Why pact stands out? What are its pros that others libraries will not have?
